/*                                                                             
  MSP430 Emulator                                                              
  Copyright (C) 2014, 2015 Rudolf Geosits (rgeosits@live.esu.edu)              

  This program is free software: you can redistribute it and/or modify         
  it under the terms of the GNU General Public License as published by         
  the Free Software Foundation, either version 3 of the License, or            
  (at your option) any later version.                                          

  This program is distributed in the hope that it will be useful,             
  but WITHOUT ANY WARRANTY; without even the implied warranty of               
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                
  GNU General Public License for more details.                                

  You should have received a copy of the GNU General Public License         
  along with this program. If not, see <http://www.gnu.org/licenses         
*/

void ports_setup () {
  *(P1IN   = (uint8_t *) get_addr_ptr(P1IN_VIRTUAL_LOC))   = 0;
  *(P1OUT  = (uint8_t *) get_addr_ptr(P1OUT_VIRTUAL_LOC))  = 0;
  *(P1DIR  = (uint8_t *) get_addr_ptr(P1DIR_VIRTUAL_LOC))  = 0;
  *(P1IFG  = (uint8_t *) get_addr_ptr(P1IFG_VIRTUAL_LOC))  = 0;
  *(P1IES  = (uint8_t *) get_addr_ptr(P1IES_VIRTUAL_LOC))  = 0;
  *(P1IE   = (uint8_t *) get_addr_ptr(P1IE_VIRTUAL_LOC))   = 0;
  *(P1SEL  = (uint8_t *) get_addr_ptr(P1SEL_VIRTUAL_LOC))  = 0;
  *(P1SEL2 = (uint8_t *) get_addr_ptr(P1SEL2_VIRTUAL_LOC)) = 0;
  *(P1REN  = (uint8_t *) get_addr_ptr(P1REN_VIRTUAL_LOC))  = 0;
}

/* POWER UP CLEAR (PUC)
 * 
 * A PUC is always generated when a POR is generated, but a POR is not 
 * generated by a PUC. The following events trigger a PUC:
 *
 * • A POR signal
 * • Watchdog timer expiration when in watchdog mode only
 * • Watchdog timer security key violation
 * • A Flash memory security key violation
 * • A CPU instruction fetch from the peripheral address range 0h to 01FFh
 */
void power_up_clear () {
  *P1OUT = *P1DIR = *P1IFG = *P1IE = *P1SEL = *P1SEL2 = *P1REN = 0;
}
